# -*- Makefile -*-
### Makefile - VHDL Makefile generated by Emacs VHDL Mode 3.38.1

# Directory : "c:/Users/cjkas/Documents/GitHub/Ensc252FinalProject/"
# Platform  : GHDL
# Generated : 2021-12-02 20:38:16 cjkas


# Define compilation command and options

COMPILE = ghdl
OPTIONS = -i --workdir=work --ieee=synopsys -fexplicit 


# Define library paths

LIBRARY-work = work


# Define library unit files

UNIT-work-c7s = \
	$(LIBRARY-work)/c7s/entity
UNIT-work-c7s-cust_seg = \
	$(LIBRARY-work)/c7s/cust_seg
UNIT-work-clockcontrol = \
	$(LIBRARY-work)/clockcontrol/entity
UNIT-work-clockcontrol-speedselect = \
	$(LIBRARY-work)/clockcontrol/speedselect


# Define list of all library unit files

ALL_UNITS = \
	$(UNIT-work-c7s) \
	$(UNIT-work-c7s-cust_seg) \
	$(UNIT-work-clockcontrol) \
	$(UNIT-work-clockcontrol-speedselect)



# Rule for compiling entire design

all : \
		library \
		$(ALL_UNITS)


# Rule for cleaning entire design

clean : 
	-rm -f $(ALL_UNITS)


# Rule for creating library directory

library : \
		$(LIBRARY-work)

$(LIBRARY-work) :
	mkdir $(LIBRARY-work)


.PHONY : all clean library


# Rules for compiling single library units and their subhierarchy

c7s : \
		library \
		$(UNIT-work-c7s) \
		$(UNIT-work-c7s-cust_seg)

clockcontrol : \
		library \
		$(UNIT-work-clockcontrol) \
		$(UNIT-work-clockcontrol-speedselect)


# Rules for compiling single library unit files

$(UNIT-work-c7s) \
$(UNIT-work-c7s-cust_seg) : \
		c7s.vhd
	$(COMPILE) $(OPTIONS) c7s.vhd

$(UNIT-work-clockcontrol) \
$(UNIT-work-clockcontrol-speedselect) : \
		clockcontrol.vhd
	$(COMPILE) $(OPTIONS) clockcontrol.vhd


### Makefile ends here
